/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasigudang;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Axioo
 */
public class FDataProduk extends javax.swing.JFrame {

    /**
     * Creates new form FDataProduk
     */
    public FDataProduk() {
        initComponents();
        load_data();
        IDOtomatis();
    }
    
    public void load_data(){
        Connection kon=koneksi.koneksiDb();
        Object header[]={"ID PRODUK","ID KATEGORI","NAMA PRODUK","HARGA","STOK"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        TabelProduk.setModel(data);
        String sql_data="SELECT * FROM tbl_produk";
        
        try
        {
            Statement st=kon.createStatement();
            ResultSet rs=st.executeQuery(sql_data);
            while(rs.next())
            {
                String d1=rs.getString(1);
                String d2=rs.getString(2);
                String d3=rs.getString(3);
                String d4=rs.getString(4);
                String d5=rs.getString(5);
                
                String d[]={d1,d2,d3,d4,d5};
                data.addRow(d);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void IDOtomatis(){
        
        try
        {
            Connection kon=koneksi.koneksiDb();
            Statement st=kon.createStatement();
            String sql_id="SELECT * FROM tbl_produk ORDER BY id_produk";
            ResultSet rs=st.executeQuery(sql_id);
            if(rs.next())
            {
                String id_produk=rs.getString("id_produk").substring(1);
                String AN=""+(Integer.parseInt(id_produk)+1);
                String Nol="";
                if(AN.length()==1)
                {
                    Nol="0000";
                }
                else if(AN.length()==2)
                {
                    Nol="000";
                }
                else if(AN.length()==3)
                {
                    Nol="00";
                }
                IDPROD.setText("A"+Nol+AN);
            }
            else
            {
                IDPROD.setText("A00001");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDPROD = new javax.swing.JTextField();
        IDKAT_DTPROD = new javax.swing.JTextField();
        NAMA_PROD = new javax.swing.JTextField();
        HARGA = new javax.swing.JTextField();
        STOK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelProduk = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA PRODUK");

        jLabel2.setText("ID_Produk");

        jLabel3.setText("ID_Kategori");

        jLabel4.setText("Nama Produk");

        jLabel5.setText("Harga");

        jLabel6.setText("Stok");

        TabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelProduk);

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("KELUAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Berdasarkan Nama");

        jButton5.setText("CARI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("REFRESH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("CETAK LAPORAN");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDPROD)
                    .addComponent(IDKAT_DTPROD)
                    .addComponent(NAMA_PROD)
                    .addComponent(HARGA)
                    .addComponent(STOK, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(398, 398, 398))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(32, 32, 32)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IDPROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDKAT_DTPROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NAMA_PROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(HARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(STOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Mengambil nilai dari kolom input
        String id_produk = IDPROD.getText();
        String id_kategori = IDKAT_DTPROD.getText();
        String nama_produk = NAMA_PROD.getText();
        String harga = HARGA.getText();
        String stok = STOK.getText();

        // Memasukkan data ke dalam database MySQL
        try {
            Connection kon = koneksi.koneksiDb();
            Statement st = kon.createStatement();

            // Query untuk menyimpan data ke dalam tabel tbl_produk
            String sql_insert = "INSERT INTO tbl_produk (id_produk, id_kategori, nama_produk, harga, stok) "
                    + "VALUES ('" + id_produk + "', '" + id_kategori + "', '" + nama_produk + "', '" + harga + "', '" + stok + "')";

            // Eksekusi query
            st.executeUpdate(sql_insert);

            // Tampilkan pesan sukses
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

            // Bersihkan kolom input
            IDPROD.setText("");
            IDKAT_DTPROD.setText("");
            NAMA_PROD.setText("");
            HARGA.setText("");
            STOK.setText("");

            // Perbarui tabel untuk menampilkan data yang telah diperbarui
            load_data();
            IDOtomatis();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Gudang_Apk().show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Mengambil nilai dari kolom input
        int selectedRow = TabelProduk.getSelectedRow();

        // Pastikan baris terpilih
        if (selectedRow != -1) {
            String id_produk = TabelProduk.getValueAt(selectedRow, 0).toString();

            // Konfirmasi penghapusan data
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    Connection kon = koneksi.koneksiDb();
                    Statement st = kon.createStatement();
                    
                    // Query untuk menghapus data dari tabel tbl_produk
                    String sql_delete = "DELETE FROM tbl_produk WHERE id_produk = '" + id_produk + "'";

                    // Eksekusi query
                    st.executeUpdate(sql_delete);

                    // Tampilkan pesan sukses
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

                    // Bersihkan kolom input
                    IDPROD.setText("");
                    IDKAT_DTPROD.setText("");
                    NAMA_PROD.setText("");
                    HARGA.setText("");
                    STOK.setText("");
                    
                    // Perbarui tabel untuk menampilkan data yang telah diperbarui
                    load_data();
                    IDOtomatis();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Mendapatkan baris yang dipilih dari tabel
        int selectedRow = TabelProduk.getSelectedRow();

        // Memastikan baris terpilih sebelum melanjutkan
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit");
            return;
        }
        
        // Mendapatkan nilai kolom dari baris terpilih
        String id_produk = TabelProduk.getValueAt(selectedRow, 0).toString();
        String id_kategori = TabelProduk.getValueAt(selectedRow, 1).toString();
        String nama_produk = TabelProduk.getValueAt(selectedRow, 2).toString();
        String harga = TabelProduk.getValueAt(selectedRow, 3).toString();
        String stok = TabelProduk.getValueAt(selectedRow, 4).toString();

        // Menampilkan dialog untuk memasukkan nilai yang baru
        String newIdKat = JOptionPane.showInputDialog(this, "Masukkan ID Kategori Baru:", id_kategori);
        String newNamaProd = JOptionPane.showInputDialog(this, "Masukkan Nama Produk Baru:", nama_produk);
        String newHarga = JOptionPane.showInputDialog(this, "Masukkan Harga Baru:", harga);
        String newStok = JOptionPane.showInputDialog(this, "Masukkan Stok Baru:", stok);
        
        // Memastikan bahwa pengguna memasukkan nilai yang valid dan tidak membatalkan input
        if (newIdKat != null && !newIdKat.isEmpty() && newNamaProd != null && !newNamaProd.isEmpty()
                && newHarga != null && !newHarga.isEmpty() && newStok != null && !newStok.isEmpty()) {

            // Update data ke dalam database MySQL
            try {
                Connection kon = koneksi.koneksiDb();
                Statement st = kon.createStatement();
                String sql_update = "UPDATE tbl_produk SET id_kategori = '" + newIdKat + "', nama_produk = '" + newNamaProd +
                                    "', harga = '" + newHarga + "', stok = '" + newStok + "' WHERE id_produk = '" + id_produk + "'";
                st.executeUpdate(sql_update);

                // Tampilkan pesan sukses
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate");

                // Perbarui tabel untuk menampilkan data yang telah diperbarui
                load_data();
                IDOtomatis();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Mendapatkan kata kunci pencarian dari TextField
        String keyword = jTextField1.getText().trim();

        // Memastikan bahwa kata kunci tidak kosong sebelum melanjutkan
        if (!keyword.isEmpty()) {
            // Melakukan pencarian berdasarkan nama produk di database MySQL
            try {
                Connection kon = koneksi.koneksiDb();
                Statement st = kon.createStatement();
                String sql_search = "SELECT * FROM tbl_produk WHERE nama_produk LIKE '%" + keyword + "%'";
                ResultSet rs = st.executeQuery(sql_search);

                // Mengisi tabel dengan hasil pencarian
                DefaultTableModel data = new DefaultTableModel();
                data.addColumn("ID PRODUK");
                data.addColumn("ID KATEGORI");
                data.addColumn("NAMA PRODUK");
                data.addColumn("HARGA");
                data.addColumn("STOK");

                while (rs.next()) {
                    String d1 = rs.getString(1);
                    String d2 = rs.getString(2);
                    String d3 = rs.getString(3);
                    String d4 = rs.getString(4);
                    String d5 = rs.getString(5);
                    String[] d = {d1, d2, d3, d4, d5};
                    data.addRow(d);
                }

                // Menampilkan hasil pencarian di tabel
                TabelProduk.setModel(data);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        } else {
            // Jika kata kunci kosong, tampilkan pesan peringatan
            JOptionPane.showMessageDialog(this, "Masukkan kata kunci pencarian");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Memanggil metode untuk merefresh data
            refreshData();
        }                                        

        // Metode untuk merefresh data
        private void refreshData() {
            // Mengosongkan kolom-kolom textfield
            IDPROD.setText("");
            IDKAT_DTPROD.setText("");
            NAMA_PROD.setText("");
            HARGA.setText("");
            STOK.setText("");
            
            // Memanggil metode load_data() untuk memuat kembali data dari database
            load_data();

            // Memanggil metode IDOtomatis() untuk memperbarui ID otomatis
            IDOtomatis();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            // Memuat JasperReport dari file .jasper yang telah dikompilasi
            InputStream reportStream = getClass().getResourceAsStream("/report/reportProduk.jasper");
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(reportStream);

            // Menyiapkan parameter untuk laporan (jika diperlukan)
            Map<String, Object> parameters = new HashMap<>();

            // Mendapatkan koneksi ke database Anda (sesuaikan sesuai dengan pengaturan database Anda)
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/dbase_gudang", "root", "");

            // Menghasilkan objek JasperPrint
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);

            // Menutup koneksi database
            conn.close();

            // Menampilkan laporan menggunakan JasperViewer
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException | java.sql.SQLException ex) {
            // Menghandle exception dengan tepat (misalnya, menampilkan pesan error)
            JOptionPane.showMessageDialog(this, "Error generating report: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDataProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HARGA;
    private javax.swing.JTextField IDKAT_DTPROD;
    private javax.swing.JTextField IDPROD;
    private javax.swing.JTextField NAMA_PROD;
    private javax.swing.JTextField STOK;
    private javax.swing.JTable TabelProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
